version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    # Ignore major version upgrades
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
